import { DEFAULT_TIER_CONFIG, type Deal, type MarketIntel, type PainPoint, type Profile, type Settings, type Task, type Team } from './model';

const DAY = 86_400_000;

function ago(days: number): string {
  return new Date(Date.now() - days * DAY).toISOString();
}

function dateAgo(days: number): string {
  return ago(days).slice(0, 10);
}

function dateFromNow(days: number): string {
  return new Date(Date.now() + days * DAY).toISOString().slice(0, 10);
}

const profiles: Profile[] = [
  { id: 'next-admin', email: 'hugh@worldsun.next', full_name: 'Hugh Lee', rm_code: 'Hugh', role: 'admin', team_id: 'next-team' },
  { id: 'next-rm-1', email: 'amy@worldsun.next', full_name: 'Amy Chen', rm_code: 'Amy', role: 'rm', team_id: 'next-team' },
  { id: 'next-rm-2', email: 'johnson@worldsun.next', full_name: 'Johnson Lin', rm_code: 'Johnson', role: 'team_lead', team_id: 'next-team' },
  { id: 'next-coo', email: 'abbie@worldsun.next', full_name: 'Abbie Wu', rm_code: 'COO', role: 'admin', team_id: 'next-team' },
];

const teams: Team[] = [
  { id: 'next-team', name: 'Next Platform Team', created_at: ago(90) },
];

const settings: Settings = {
  id: 1,
  stage_probs: { L1: 7, L2: 13, L3: 20, L4: 44, L5: 68, L6: 90, L7: 100 },
  red_flag: { ebScore: 4, totalScore: 40, staleDays: 30, contactWarnDays: 14 },
  tier_config: { tiers: DEFAULT_TIER_CONFIG },
};

const deals: Deal[] = [
  {
    id: 'next-wang-family',
    name: '王家控股傳承案',
    rm_id: 'next-admin',
    aum_usd: 82_000_000,
    product: '香港分紅保單 + 百慕達信託架構',
    first_contact: dateAgo(76),
    last_updated: ago(4),
    last_contact_at: ago(19),
    tier: 'SSS',
    stage: 'L5',
    next_step: '約王董與太太確認最終受益人排序\n請會計師先看 KYC 與資金來源文件\n準備 EB 版本的一頁式風險說明',
    target_close_date: dateFromNow(38),
    created_at: ago(76),
    plan: {
      target_date: dateFromNow(38),
      generated_at: ago(3),
      model: 'standalone-prototype',
      overview: '先把家族決策人和文件流程鎖死，再進入簽署與核保。',
      feasibility: 'medium',
      feasibility_reason: 'EB 已出現，但 Paper Process 還有文件缺口。',
      top_risks: ['太太對受益人安排仍保留', '資金來源文件需會計師補強'],
      steps: [
        {
          id: 'wang-step-1',
          title: '完成 EB 家族會議',
          target_date: dateFromNow(7),
          stage_transition: 'L5 hold',
          focus: ['邀請太太一起看最終摘要', '確認受益人順位'],
          talking_points: ['這次不是選商品，是把家族未來的決策權整理清楚。'],
          risks: ['若太太未參與，後面簽署可能重開討論'],
          completed: false,
          completed_at: null,
        },
        {
          id: 'wang-step-2',
          title: '啟動文件清單與時間表',
          target_date: dateFromNow(14),
          stage_transition: 'L5 -> L6',
          focus: ['列出 KYC 與資金來源清單', '請會計師確認可交付日期'],
          talking_points: ['文件不只是行政流程，它會決定整案落地時間。'],
          risks: ['公司戶資料不齊'],
          completed: false,
          completed_at: null,
        },
      ],
    },
    scores: { m: 8, e: 6, d1: 7, d2: 5, p: 3, i: 8, c1: 5, c2: 6 },
    score_notes: [
      { deal_id: 'next-wang-family', field: 'p', evidence: '會計師尚未確認資金來源文件格式。', next_action: '本週寄 checklist。' },
      { deal_id: 'next-wang-family', field: 'e', evidence: '王董可拍板，但太太會影響受益人安排。', next_action: '安排夫妻會議。' },
    ],
    stage_checklist: [],
    comments: [
      { id: 'comment-wang-1', deal_id: 'next-wang-family', author_id: 'next-admin', body: '王董重視傳承公平，太太更在意控制權不要太早交出去。', is_system: false, is_raw: false, created_at: ago(5) },
    ],
    deal_questions: [],
    deal_attachments: [],
    rm: profiles[0],
  },
  {
    id: 'next-lin-liquidity',
    name: '林董公司戶流動性案',
    rm_id: 'next-rm-2',
    aum_usd: 28_000_000,
    product: '宏利公司戶保費融資',
    first_contact: dateAgo(42),
    last_updated: ago(18),
    last_contact_at: ago(18),
    tier: 'A',
    stage: 'L4',
    next_step: '補一版保守情境 IRR\n請 CFO 提供公司戶董事會流程',
    target_close_date: dateFromNow(45),
    created_at: ago(42),
    plan: null,
    scores: { m: 7, e: 4, d1: 6, d2: 3, p: 2, i: 7, c1: 6, c2: 4 },
    score_notes: [
      { deal_id: 'next-lin-liquidity', field: 'd2', evidence: 'CFO 說董事會流程可能 3-4 週。', next_action: '畫出決策流程圖。' },
    ],
    stage_checklist: [],
    comments: [],
    deal_questions: [],
    deal_attachments: [],
    rm: profiles[2],
  },
  {
    id: 'next-chen-fcn',
    name: '陳家股票收益案',
    rm_id: 'next-rm-1',
    aum_usd: 9_500_000,
    product: 'FCN / BEN 分批進場策略',
    first_contact: dateAgo(23),
    last_updated: ago(2),
    last_contact_at: ago(6),
    tier: 'B',
    stage: 'L3',
    next_step: '確認客戶可接受的下檔股票清單\n把券商條件和私銀報價放同表比較',
    target_close_date: null,
    created_at: ago(23),
    plan: null,
    scores: { m: 6, e: 7, d1: 5, d2: 5, p: 4, i: 6, c1: 3, c2: 5 },
    score_notes: [],
    stage_checklist: [],
    comments: [
      { id: 'comment-chen-1', deal_id: 'next-chen-fcn', author_id: 'next-rm-1', body: '客戶怕追高，願意用票息等待進場。', is_system: false, is_raw: false, created_at: ago(2) },
    ],
    deal_questions: [],
    deal_attachments: [],
    rm: profiles[1],
  },
  {
    id: 'next-hsu-retirement',
    name: '許醫師退休現金流案',
    rm_id: 'next-admin',
    aum_usd: 4_200_000,
    product: '美元分紅保單',
    first_contact: dateAgo(12),
    last_updated: ago(1),
    last_contact_at: ago(1),
    tier: 'C',
    stage: 'L2',
    next_step: '下次會面確認每月被動現金流需求',
    target_close_date: null,
    created_at: ago(12),
    plan: null,
    scores: { m: 3, e: 2, d1: 2, d2: 1, p: 0, i: 4, c1: 0, c2: 1 },
    score_notes: [],
    stage_checklist: [],
    comments: [],
    deal_questions: [],
    deal_attachments: [],
    rm: profiles[0],
  },
];

const tasks: Task[] = [
  {
    id: 'task-wang-eb',
    deal_id: 'next-wang-family',
    title: '安排王董夫妻 EB 會議',
    description: '',
    assignee_id: 'next-admin',
    due_date: dateFromNow(2),
    status: 'todo',
    priority: 'high',
    source_type: 'manual',
    source_ref: '',
    created_by: 'next-coo',
    created_at: ago(1),
    completed_at: null,
  },
  {
    id: 'task-wang-kyc',
    deal_id: 'next-wang-family',
    title: '寄出王家 KYC / 資金來源文件清單',
    description: '先給會計師版本，再整理成家族會議用的一頁 checklist。',
    assignee_id: 'next-rm-2',
    due_date: dateFromNow(4),
    status: 'doing',
    priority: 'normal',
    source_type: 'manual',
    source_ref: '',
    created_by: 'next-coo',
    created_at: ago(2),
    completed_at: null,
  },
  {
    id: 'task-wang-summary',
    deal_id: 'next-wang-family',
    title: '完成王董傳承架構摘要初稿',
    description: '',
    assignee_id: 'next-admin',
    due_date: dateAgo(1),
    status: 'done',
    priority: 'high',
    source_type: 'ai_plan_step',
    source_ref: 'wang-step-1',
    created_by: 'next-admin',
    created_at: ago(5),
    completed_at: ago(1),
  },
  {
    id: 'task-lin-cfo',
    deal_id: 'next-lin-liquidity',
    title: '請 CFO 補董事會流程',
    description: '',
    assignee_id: 'next-rm-2',
    due_date: dateAgo(2),
    status: 'doing',
    priority: 'high',
    source_type: 'manual',
    source_ref: '',
    created_by: 'next-admin',
    created_at: ago(6),
    completed_at: null,
  },
  {
    id: 'task-lin-irr',
    deal_id: 'next-lin-liquidity',
    title: '補一版保守情境 IRR 壓測',
    description: 'COO 明早會議前需要看 worst case / base case / upside。',
    assignee_id: 'next-rm-2',
    due_date: dateFromNow(3),
    status: 'todo',
    priority: 'normal',
    source_type: 'deal_next_step',
    source_ref: 'next-lin-liquidity',
    created_by: 'next-coo',
    created_at: ago(1),
    completed_at: null,
  },
  {
    id: 'task-lin-board',
    deal_id: 'next-lin-liquidity',
    title: '確認林董公司戶董事會簽核節點',
    description: '',
    assignee_id: 'next-coo',
    due_date: dateFromNow(6),
    status: 'todo',
    priority: 'high',
    source_type: 'manual',
    source_ref: '',
    created_by: 'next-admin',
    created_at: ago(1),
    completed_at: null,
  },
  {
    id: 'task-chen-quote',
    deal_id: 'next-chen-fcn',
    title: '整理 FCN / BEN 報價比較表',
    description: '',
    assignee_id: 'next-rm-1',
    due_date: dateFromNow(5),
    status: 'todo',
    priority: 'normal',
    source_type: 'manual',
    source_ref: '',
    created_by: 'next-rm-1',
    created_at: ago(2),
    completed_at: null,
  },
  {
    id: 'task-chen-stocklist',
    deal_id: 'next-chen-fcn',
    title: '確認陳家可接受的下檔股票清單',
    description: '',
    assignee_id: 'next-rm-1',
    due_date: dateFromNow(1),
    status: 'doing',
    priority: 'high',
    source_type: 'deal_next_step',
    source_ref: 'next-chen-fcn',
    created_by: 'next-coo',
    created_at: ago(2),
    completed_at: null,
  },
  {
    id: 'task-hsu-cashflow',
    deal_id: 'next-hsu-retirement',
    title: '整理許醫師退休現金流需求表',
    description: '',
    assignee_id: 'next-admin',
    due_date: dateFromNow(7),
    status: 'todo',
    priority: 'low',
    source_type: 'manual',
    source_ref: '',
    created_by: 'next-coo',
    created_at: ago(1),
    completed_at: null,
  },
  {
    id: 'task-hsu-follow-up',
    deal_id: 'next-hsu-retirement',
    title: '完成許醫師初談紀錄整理',
    description: '',
    assignee_id: 'next-admin',
    due_date: dateAgo(1),
    status: 'done',
    priority: 'normal',
    source_type: 'manual',
    source_ref: '',
    created_by: 'next-admin',
    created_at: ago(3),
    completed_at: ago(1),
  },
  {
    id: 'task-coo-weekly-report',
    deal_id: null,
    title: '彙整本週 pipeline 例會追蹤清單',
    description: '把 L4+、逾期聯繫、文件流程卡關案件列成 COO 會議表。',
    assignee_id: 'next-coo',
    due_date: dateFromNow(0),
    status: 'doing',
    priority: 'high',
    source_type: 'manual',
    source_ref: '',
    created_by: 'next-admin',
    created_at: ago(1),
    completed_at: null,
  },
  {
    id: 'task-coo-resend',
    deal_id: null,
    title: '確認 Resend 網域驗證進度',
    description: '',
    assignee_id: 'next-coo',
    due_date: dateFromNow(4),
    status: 'todo',
    priority: 'normal',
    source_type: 'manual',
    source_ref: '',
    created_by: 'next-admin',
    created_at: ago(4),
    completed_at: null,
  },
  {
    id: 'task-product-library',
    deal_id: null,
    title: '更新 pain-to-product 話術庫',
    description: '補上公司戶保費融資、FCN / BEN、傳承架構三類話術。',
    assignee_id: 'next-admin',
    due_date: dateFromNow(6),
    status: 'todo',
    priority: 'normal',
    source_type: 'manual',
    source_ref: '',
    created_by: 'next-coo',
    created_at: ago(2),
    completed_at: null,
  },
  {
    id: 'task-market-signal-review',
    deal_id: null,
    title: '挑選三則可用於客戶 follow-up 的市場訊號',
    description: '',
    assignee_id: 'next-coo',
    due_date: dateFromNow(2),
    status: 'todo',
    priority: 'low',
    source_type: 'manual',
    source_ref: '',
    created_by: 'next-coo',
    created_at: ago(1),
    completed_at: null,
  },
  {
    id: 'task-risk-review',
    deal_id: null,
    title: '逐一確認 L4+ 案件是否有 EB / Paper Process 缺口',
    description: '',
    assignee_id: 'next-admin',
    due_date: dateAgo(1),
    status: 'todo',
    priority: 'high',
    source_type: 'manual',
    source_ref: '',
    created_by: 'next-coo',
    created_at: ago(3),
    completed_at: null,
  },
];

const painPoints: PainPoint[] = [
  { id: 'pain-1', pain: '擔心家族傳承失衡', product: '香港分紅保單 + 信託架構', pitch: '用受益人與控制權安排降低家族爭議。', tiers: 'S/SSS', order_idx: 10, is_active: true },
  { id: 'pain-2', pain: '公司資金閒置但不想失去流動性', product: '公司戶保費融資', pitch: '讓公司戶資金保留彈性，同時建立長期保單資產。', tiers: 'A/S', order_idx: 20, is_active: true },
  { id: 'pain-3', pain: '看好股票但不想追高', product: 'FCN / BEN', pitch: '用票息與折價條件等待進場。', tiers: 'B/A', order_idx: 30, is_active: true },
];

const marketIntel: MarketIntel[] = [
  {
    id: 'intel-rates',
    title: '美元利率維持高檔，保費融資敏感度需重新壓測',
    source_type: 'media',
    source_name: 'Standalone Signal Desk',
    source_url: '',
    region: 'GLOBAL',
    summary: '高利率環境讓融資結構更需要保守情境，適合對 L4-L6 客戶重做利差壓測。',
    key_points: ['融資利差敏感度上升', '晚期案件需補 stress test'],
    stance: 'neutral',
    author: 'Prototype',
    published_at: dateAgo(1),
    source_origin: 'manual',
    created_by: 'next-admin',
    created_at: ago(1),
    updated_at: ago(1),
    tags: [{ id: 'tag-rates', name: 'Rates', category: 'macro' }],
    deal_links: [{ deal_id: 'next-lin-liquidity', relevance_reason: '保費融資案需更新壓測', deal: { id: 'next-lin-liquidity', name: '林董公司戶流動性案' } }],
    creator: { full_name: 'Prototype' },
  },
  {
    id: 'intel-hk-insurance',
    title: '香港分紅保單買盤回溫，高資產家族重新關注傳承工具',
    source_type: 'internal',
    source_name: 'Standalone Internal Note',
    source_url: '',
    region: 'GLOBAL',
    summary: '近期高資產客戶討論重點從收益轉回控制權、受益人安排與跨代治理。',
    key_points: ['傳承需求回溫', 'EB 與配偶共同決策更重要'],
    stance: 'bullish',
    author: 'Prototype',
    published_at: dateAgo(3),
    source_origin: 'manual',
    created_by: 'next-admin',
    created_at: ago(3),
    updated_at: ago(3),
    tags: [{ id: 'tag-succession', name: 'Succession', category: 'theme' }],
    deal_links: [{ deal_id: 'next-wang-family', relevance_reason: '傳承架構討論可引用', deal: { id: 'next-wang-family', name: '王家控股傳承案' } }],
    creator: { full_name: 'Prototype' },
  },
];

export function getV2WorkspaceData() {
  return {
    profile: profiles[3],
    profiles,
    teams,
    settings,
    deals,
    tasks,
    painPoints,
    marketIntel,
  };
}
